name:                fix-module
version:             0.1.0.0
github:              "YusukeHosonuma/fix-module"
license:             MIT
author:              "Yusuke Hosonuma"
maintainer:          "tobi462@gmail.com"
copyright:           "2021 Yusuke Hosonuma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YusukeHosonuma/fix-module#README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - extra
  - filepath
  - text
  - unordered-containers
  - yaml

executables:
  fix-module:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - fix-module
    - directory

tests:
  fix-module-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - fix-module
    - tasty
    - tasty-hunit
    - process
